apiVersion: v1
kind: Service
metadata:
  name: ecr-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: ecr
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
